# Visualization

In [18]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import folium
import webbrowser

In [3]:
data = pd.read_csv("Data/us_daily_processed.csv")
data.head()

,Unnamed: 0,date,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active
0,0,01-22-2020,NaN,NaN,NaN,US,1/22/2020 17:00,NaN,NaN,1,NaN,NaN,NaN
1,1,01-23-2020,NaN,NaN,NaN,US,1/23/20 17:00,NaN,NaN,1,NaN,NaN,NaN
2,2,01-24-2020,NaN,NaN,NaN,US,1/24/20 17:00,NaN,NaN,1,NaN,NaN,NaN
3,3,01-24-2020,NaN,NaN,NaN,US,1/24/20 17:00,NaN,NaN,1,NaN,NaN,NaN
4,4,01-25-2020,NaN,NaN,NaN,US,1/25/20 17:00,NaN,NaN,1,NaN,NaN,NaN

In [4]:
d_test=data.groupby(["Province_State","date"])[['Confirmed','Deaths']].sum().reset_index()
d_test.head()

  Province_State        date  Confirmed  Deaths
0        Alabama  03-14-2020          6     0.0
1        Alabama  03-15-2020         12     0.0
2        Alabama  03-16-2020         29     0.0
3        Alabama  03-17-2020         39     0.0
4        Alabama  03-18-2020         46     0.0

In [5]:
d_total = d_test.groupby(["Province_State"])[['Confirmed','Deaths']].sum().reset_index()
nd = np.shape(d_total)[0]
d_total

    Province_State  Confirmed   Deaths
0          Alabama     386151  14314.0
1           Alaska      18193    478.0
2   American Samoa          0      0.0
3          Arizona     428539  18760.0
4         Arkansas     160569   3289.0
..             ...        ...      ...
59      Washington     786468  41683.0
60   West Virginia      55681   1904.0
61       Wisconsin     392811  15545.0
62   Wuhan Evacuee          4      0.0
63         Wyoming      27224    276.0

[64 rows x 3 columns]

In [6]:
cluster_data = pd.read_csv("Data/useful_features_by_state.csv")

In [7]:
cluster_data.columns

Index(['state', 'beds', '2019', 'State', 'Latitude', 'Longitude'], dtype='object')

In [8]:
cluster_data

                   state       beds        2019 State   Latitude   Longitude
0                 Alaska   4.789014    731545.0    AK  61.302501 -158.775020
1                Alabama  11.967593   4903185.0    AL  32.601011  -86.680736
2               Arkansas   8.403947   3017804.0    AR  34.751928  -92.131378
3                Arizona   2.050268   7278717.0    AZ  34.168219 -111.930907
4             California   8.182707  39512223.0    CA  37.271875 -119.270415
5               Colorado   4.159082   5758736.0    CO  38.997934 -105.550567
6            Connecticut   2.157418   3565287.0    CT  41.518784  -72.757507
7   District of Columbia   0.466990    705749.0    DC  38.899349  -77.014567
8               Delaware   0.558183    973764.0    DE  39.145251  -75.418921
9                Florida  12.315425  21477737.0    FL  27.975728  -83.833017
10               Georgia  20.157662  10617423.0    GA  32.678125  -83.222976
11                Hawaii   0.520208   1415872.0    HI  20.460000 -157.505000
12                  Iowa   4.386061   3155070.0    IA  41.938317  -93.389798
13                 Idaho   2.516173   1787065.0    ID  45.494576 -114.142430
14              Illinois   9.060001  12671821.0    IL  39.739318  -89.504139
15               Indiana  11.234091   6732219.0    IN  39.766219  -86.441277
16                Kansas   6.782206   2913314.0    KS  38.498779  -98.320078
17              Kentucky  16.519195   4467673.0    KY  37.822294  -85.768240
18             Louisiana   9.872175   4648794.0    LA  30.973377  -91.429910
19         Massachusetts   2.144799   6892503.0    MA  42.062940  -71.718067
20              Maryland   3.508960   6045680.0    MD  38.806352  -77.268416
21                 Maine  27.528036   1344212.0    ME  45.218513  -69.014866
22              Michigan  11.808355   9986857.0    MI  44.943560  -86.415805
23             Minnesota   5.658129   5639632.0    MN  46.441859  -93.365515
24              Missouri  10.781061   6137428.0    MO  38.304662  -92.437099
25           Mississippi  11.363654   2976149.0    MS  32.585106  -89.877220
26               Montana   3.571003   1068778.0    MT  46.679800 -110.044783
27        North Carolina  15.006825  10488084.0    NC  35.214563  -79.891267
28          North Dakota   1.800766    762062.0    ND  47.467882 -100.302266
29              Nebraska   4.385605   1934408.0    NE  41.500819  -99.680902
30         New Hampshire   1.937659   1359711.0    NH  44.001231  -71.579923
31            New Jersey   5.342430   8882190.0    NJ  40.143006  -74.731116
32            New Mexico   2.960478   2096829.0    NM  34.166232 -106.026068
33                Nevada   1.748019   3080156.0    NV  38.502032 -117.023060
34              New York   8.382213  19453561.0    NY  43.000000  -75.000000
35                  Ohio  11.948555  11689100.0    OH  40.190362  -82.669252
36              Oklahoma   7.896221   3956971.0    OK  35.309765  -98.716559
37                Oregon   3.407778   4217737.0    OR  44.141905 -120.538099
38          Pennsylvania  14.260610  12801989.0    PA  40.994593  -77.604698
39          Rhode Island   0.720353   1059361.0    RI  41.582728  -71.506451
40        South Carolina   7.950473   5148714.0    SC  33.625050  -80.947038
41          South Dakota   2.378135    884659.0    SD  44.212699 -100.247164
42             Tennessee  12.886517   6829174.0    TN  35.830521  -85.978599
43                 Texas  27.502458  28995881.0    TX  31.169336 -100.076842
44                  Utah   2.713359   3205958.0    UT  39.499761 -111.547028
45              Virginia  25.947822   8535519.0    VA  38.003386  -79.458786
46               Vermont   1.019483    623989.0    VT  43.871755  -72.447783
47            Washington   2.495058   7614893.0    WA  47.000000 -120.000000
48             Wisconsin   8.461720   5822434.0    WI  44.786297  -89.826705
49         West Virginia   8.690672   1792147.0    WV  38.920171  -80.181691
50               Wyoming   2.163612    578759.0    WY  43.000325 -107.554567

In [9]:
states = list(set(cluster_data['state']))

In [10]:
for i in range(nd):
    item = d_total.loc[i,'Province_State']
    if item not in states:
        d_total = d_total.drop([i],axis=0)
d_total = d_total.reset_index().drop(['index'],axis=1)

In [11]:
d_total

          Province_State  Confirmed     Deaths
0                Alabama     386151    14314.0
1                 Alaska      18193      478.0
2                Arizona     428539    18760.0
3               Arkansas     160569     3289.0
4             California    2641552   101180.0
5               Colorado     762353    37547.0
6            Connecticut    1313927   104176.0
7               Delaware     233935     7810.0
8   District of Columbia     229578    10820.0
9                Florida    1722112    63026.0
10               Georgia    1327509    54547.0
11                Hawaii      31463      675.0
12                 Idaho     102079     2767.0
13              Illinois    2837818   121161.0
14               Indiana     906439    52325.0
15                  Iowa     396380     9176.0
16                Kansas     231082     6607.0
17              Kentucky     242556    11581.0
18             Louisiana    1440585    90534.0
19                 Maine      61215     2446.0
20              Maryland    1169417    55391.0
21         Massachusetts    2928019   167042.0
22              Michigan    2024809   171543.0
23             Minnesota     377589    18923.0
24           Mississippi     358455    15044.0
25              Missouri     400725    17947.0
26               Montana      23727      677.0
27              Nebraska     255913     3376.0
28                Nevada     258850    11805.0
29         New Hampshire     116089     4430.0
30            New Jersey    5648175   333533.0
31            New Mexico     177000     6804.0
32              New York   14860848  1056761.0
33        North Carolina     577120    19643.0
34          North Dakota      55855     1209.0
35                  Ohio     908773    47901.0
36              Oklahoma     187349    10391.0
37                Oregon     134464     5044.0
38          Pennsylvania    2316401   125885.0
39          Rhode Island     400700    14210.0
40        South Carolina     312788    11826.0
41          South Dakota     122281     1120.0
42             Tennessee     591384    10186.0
43                 Texas    1534221    40425.0
44                  Utah     245332     2452.0
45               Vermont      45211     2343.0
46              Virginia     866689    28733.0
47            Washington     786468    41683.0
48         West Virginia      55681     1904.0
49             Wisconsin     392811    15545.0
50               Wyoming      27224      276.0

In [12]:
temp = cluster_data
temp['2019'] = temp['2019'].astype(float)
temp = pd.merge(temp, d_total, how='outer', left_on='state',right_on='Province_State')

In [13]:
temp['Death_rate'] = temp['Deaths']/temp['Confirmed']

In [14]:
state_geo = 'Data/us-states.json'

In [15]:
temp

,state,beds,2019,State,Latitude,Longitude,Province_State,Confirmed,Deaths,Death_rate
0,Alaska,4.789014,731545.0,AK,61.302501,-158.775020,Alaska,18193,478.0,0.026274
1,Alabama,11.967593,4903185.0,AL,32.601011,-86.680736,Alabama,386151,14314.0,0.037068
2,Arkansas,8.403947,3017804.0,AR,34.751928,-92.131378,Arkansas,160569,3289.0,0.020483
3,Arizona,2.050268,7278717.0,AZ,34.168219,-111.930907,Arizona,428539,18760.0,0.043777
4,California,8.182707,39512223.0,CA,37.271875,-119.270415,California,2641552,101180.0,0.038303
5,Colorado,4.159082,5758736.0,CO,38.997934,-105.550567,Colorado,762353,37547.0,0.049251
6,Connecticut,2.157418,3565287.0,CT,41.518784,-72.757507,Connecticut,1313927,104176.0,0.079286
7,District of Columbia,0.466990,705749.0,DC,38.899349,-77.014567,District of Columbia,229578,10820.0,0.047130
8,Delaware,0.558183,973764.0,DE,39.145251,-75.418921,Delaware,233935,7810.0,0.033385
9,Florida,12.315425,21477737.0,FL,27.975728,-83.833017,Florida,1722112,63026.0,0.036598
10,Georgia,20.157662,10617423.0,GA,32.678125,-83.222976,Georgia,1327509,54547.0,0.041090
11,Hawaii,0.520208,1415872.0,HI,20.460000,-157.505000,Hawaii,31463,675.0,0.021454
12,Iowa,4.386061,3155070.0,IA,41.938317,-93.389798,Iowa,396380,9176.0,0.023150
13,Idaho,2.516173,1787065.0,ID,45.494576,-114.142430,Idaho,102079,2767.0,0.027106
14,Illinois,9.060001,12671821.0,IL,39.739318,-89.504139,Illinois,2837818,121161.0,0.042695
15,Indiana,11.234091,6732219.0,IN,39.766219,-86.441277,Indiana,906439,52325.0,0.057726
16,Kansas,6.782206,2913314.0,KS,38.498779,-98.320078,Kansas,231082,6607.0,0.028592
17,Kentucky,16.519195,4467673.0,KY,37.822294,-85.768240,Kentucky,242556,11581.0,0.047746
18,Louisiana,9.872175,4648794.0,LA,30.973377,-91.429910,Louisiana,1440585,90534.0,0.062845
19,Massachusetts,2.144799,6892503.0,MA,42.062940,-71.718067,Massachusetts,2928019,167042.0,0.057049
20,Maryland,3.508960,6045680.0,MD,38.806352,-77.268416,Maryland,1169417,55391.0,0.047366
21,Maine,27.528036,1344212.0,ME,45.218513,-69.014866,Maine,61215,2446.0,0.039958
22,Michigan,11.808355,9986857.0,MI,44.943560,-86.415805,Michigan,2024809,171543.0,0.084721
23,Minnesota,5.658129,5639632.0,MN,46.441859,-93.365515,Minnesota,377589,18923.0,0.050115
24,Missouri,10.781061,6137428.0,MO,38.304662,-92.437099,Missouri,400725,17947.0,0.044786
25,Mississippi,11.363654,2976149.0,MS,32.585106,-89.877220,Mississippi,358455,15044.0,0.041969
26,Montana,3.571003,1068778.0,MT,46.679800,-110.044783,Montana,23727,677.0,0.028533
27,North Carolina,15.006825,10488084.0,NC,35.214563,-79.891267,North Carolina,577120,19643.0,0.034036
28,North Dakota,1.800766,762062.0,ND,47.467882,-100.302266,North Dakota,55855,1209.0,0.021645
29,Nebraska,4.385605,1934408.0,NE,41.500819,-99.680902,Nebraska,255913,3376.0,0.013192
30,New Hampshire,1.937659,1359711.0,NH,44.001231,-71.579923,New Hampshire,116089,4430.0,0.038160
31,New Jersey,5.342430,8882190.0,NJ,40.143006,-74.731116,New Jersey,5648175,333533.0,0.059051
32,New Mexico,2.960478,2096829.0,NM,34.166232,-106.026068,New Mexico,177000,6804.0,0.038441
33,Nevada,1.748019,3080156.0,NV,38.502032,-117.023060,Nevada,258850,11805.0,0.045606
34,New York,8.382213,19453561.0,NY,43.000000,-75.000000,New York,14860848,1056761.0,0.071110
35,Ohio,11.948555,11689100.0,OH,40.190362,-82.669252,Ohio,908773,47901.0,0.052710
36,Oklahoma,7.896221,3956971.0,OK,35.309765,-98.716559,Oklahoma,187349,10391.0,0.055463
37,Oregon,3.407778,4217737.0,OR,44.141905,-120.538099,Oregon,134464,5044.0,0.037512
38,Pennsylvania,14.260610,12801989.0,PA,40.994593,-77.604698,Pennsylvania,2316401,125885.0,0.054345
39,Rhode Island,0.720353,1059361.0,RI,41.582728,-71.506451,Rhode Island,400700,14210.0,0.035463
40,South Carolina,7.950473,5148714.0,SC,33.625050,-80.947038,South Carolina,312788,11826.0,0.037808
41,South Dakota,2.378135,884659.0,SD,44.212699,-100.247164,South Dakota,122281,1120.0,0.009159
42,Tennessee,12.886517,6829174.0,TN,35.830521,-85.978599,Tennessee,591384,10186.0,0.017224
43,Texas,27.502458,28995881.0,TX,31.169336,-100.076842,Texas,1534221,40425.0,0.026349
44,Utah,2.713359,3205958.0,UT,39.499761,-111.547028,Utah,245332,2452.0,0.009995
45,Virginia,25.947822,8535519.0,VA,38.003386,-79.458786,Virginia,866689,28733.0,0.033153
46,Vermont,1.019483,623989.0,VT,43.871755,-72.447783,Vermont,45211,2343.0,0.051824
47,Washington,2.495058,7614893.0,WA,47.000000,-120.000000,Washington,786468,41683.0,0.053000
48,Wisconsin,8.461720,5822434.0,WI,44.786297,-89.826705,Wisconsin,392811,15545.0,0.039574
49,West Virginia,8.690672,1792147.0,WV,38.920171,-80.181691,West Virginia,55681,1904.0,0.034195
50,Wyoming,2.163612,578759.0,WY,43.000325,-107.554567,Wyoming,27224,276.0,0.010138

In [22]:
#Population and confirmed case
m = folium.Map(location=[0, 0], tiles='cartodbpositron',
               min_zoom=1, max_zoom=8, zoom_start=1.5)

m.choropleth(geo_data=state_geo, name='choropleth',data=temp,
             columns=['State','2019'],
             key_on='feature.id',
             # 'BuGn', 'BuPu', 'GnBu', 'OrRd', 'PuBu', 'PuBuGn', 'PuRd', 'RdPu','YlGn', 'YlGnBu', 'YlOrBr', and 'YlOrRd'.
             fill_color='OrRd', fill_opacity=0.7, line_opacity=0.1,
             legend_name="Population")

m

for i in range(0, len(temp)):
    folium.Circle(
        location=[temp.iloc[i]['Latitude'], temp.iloc[i]['Longitude']],
        color='crimson', fill='crimson',
        tooltip =   '<li><bold>State : '+str(temp.iloc[i]['state'])+
                    '<li><bold>Polutation : '+str(temp.iloc[i]['2019'])+
                    '<li><bold>Total confirmed : '+str(temp.iloc[i]['Confirmed'])
        ,
        radius=int(temp.iloc[i]['Confirmed']*0.01)).add_to(m)

#Save 
m.save('Plots/Population_and_confirmed_case.html') 
#Show
webbrowser.open("Plots/Population_and_confirmed_case.html")

True

The first map we got shows the Population (published by census in 2019) and confirmed cases of each state. In our map, The different color corresponds to different levels of populations and the radius of the circle is proportional to the number of confirmed case. And when we move the mouse to the circle, we can see the exact value.<p> Generally speaking, states with smaller populations also have fewer confirmed case. And the situation in New York is the worst.

In [23]:
max_confirmed = np.max(temp['Confirmed'])
min_conformed = np.min(temp['Confirmed'])
print(max_confirmed,min_conformed)

14860848 18193

In [24]:
#Condirmed case and death case
m = folium.Map(location=[0, 0], tiles='cartodbpositron',
               min_zoom=1, max_zoom=8, zoom_start=1.5)

m.choropleth(geo_data=state_geo, name='choropleth',data=temp,
             columns=['State','Confirmed'],
             key_on='feature.id',
             # 'BuGn', 'BuPu', 'GnBu', 'OrRd', 'PuBu', 'PuBuGn', 'PuRd', 'RdPu','YlGn', 'YlGnBu', 'YlOrBr', and 'YlOrRd'.
             fill_color='RdPu', fill_opacity=0.7, line_opacity=0.1,
             legend_name="Confirmed cases",
             threshold_scale =[18192,100000,1000000,5000000,10000000,14860849])


m

for i in range(0, len(temp)):
    folium.Circle(
        location=[temp.iloc[i]['Latitude'], temp.iloc[i]['Longitude']],
        color='crimson', fill='crimson',
        tooltip =   '<li><bold>State : '+str(temp.iloc[i]['state'])+
                    '<li><bold>Total confirmed : '+str(temp.iloc[i]['Confirmed'])+
                     '<li><bold>Total deaths : '+str(temp.iloc[i]['Deaths'])
        ,
        radius=int(temp.iloc[i]['Deaths']*0.2)).add_to(m)

#Save 
m.save('Plots/Condirmed_case_and_death_case.html') 
#Show
webbrowser.open("Plots/Condirmed_case_and_death_case.html")

True

This map shows different levels of confirmed cases and death cases for each state. We can see that New York and New Jersey has the most confirmed cases while Massachusetts, Connecticut, Pennsylvania, Maryland, Michigan, Illinois, Texas, Louisiana, Florida, Georgia and California also has more than 1000000 confirmed cases each.<p>
Generally speaking, the epidemic is more serious in coastal states.

In [25]:
#Hopsital Beds and Death Rate
m = folium.Map(location=[0, 0], tiles='cartodbpositron',
               min_zoom=1, max_zoom=8, zoom_start=1.5)

m.choropleth(geo_data=state_geo, name='choropleth',data=temp,
             columns=['State','beds'],
             key_on='feature.id',
             # 'BuGn', 'BuPu', 'GnBu', 'OrRd', 'PuBu', 'PuBuGn', 'PuRd', 'RdPu','YlGn', 'YlGnBu', 'YlOrBr', and 'YlOrRd'.
             fill_color='GnBu', fill_opacity=0.7, line_opacity=0.1,
             legend_name="Hospital beds (per 1000 residents)")

m

for i in range(0, len(temp)):
    folium.Circle(
        location=[temp.iloc[i]['Latitude'], temp.iloc[i]['Longitude']],
        color='crimson', fill='crimson',
        tooltip =   '<li><bold>State : '+str(temp.iloc[i]['state'])+
                    '<li><bold>Hospital beds (per 1000 residents) : '+str(temp.iloc[i]['beds'])+
                    '<li><bold>Death_rate : '+str(temp.iloc[i]['Death_rate'])
        ,
        radius=int(temp.iloc[i]['Death_rate']*500000)).add_to(m)

#Save 
m.save('Plots/Hopsital_Beds_and_Death_Rate.html') 
#Show
webbrowser.open("Plots/Hopsital_Beds_and_Death_Rate.html")

True

We try to use hospital beds holds for per 1000 residents in each state to represent corresponding local medical resourse. <p>
For state with high hospital beds level like Texas and Virginia, although it has much confirmed case, but its death rate is not so high.